### ISSUE TITLE
dynamicDateSize not working

### ISSUE THREAD

**Issue by tie82** [mzeryck/Weather-Cal#89]
Hi,

dynamicDateSize is enabled, but 2 date lines are shown even with events present
![38087295-74E1-4B89-8B57-80B72763FD1D](https://user-images.githubusercontent.com/38699731/101398026-c6d17900-38cd-11eb-8706-c4c304d6ee6a.jpeg)

Thanks

**Comment by mzeryck** [comment]
I'm sorry for the delay in response! Good catch, I had updated some event code which broke this feature. Please try running "Update code", it should work now!

**Comment by adamengineering** [comment]
@mzeryck Updated, but at least in my case it seems to be still broken and furthermore I noticed that all-day events are not shown either...

**Comment by icsAT** [comment]
@adamengineering did you set "Show all-day events" to "true"? It's showing the all day events in my widgets.

**Comment by mzeryck** [comment]
@adamengineering I am curious about this as well, as I'm not seeing this bug either, so more details are appreciated.

**Comment by mzeryck** [comment]
I am closing this issue as it has been more than 7 days.
